version: '3.8'

services:
  menu-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/food_ordering_menus
      - USER_SERVICE_URL=http://localhost:8000
      - ORDER_SERVICE_URL=http://localhost:3002
    depends_on:
      - mongodb
    networks:
      - menu-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - menu-network
    restart: unless-stopped

networks:
  menu-network:
    name: menu-network
    driver: bridge

volumes:
  mongodb_data: