version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000/api
        - VITE_MENU_SERVICE_URL=http://localhost:3001
        - VITE_ORDER_SERVICE_URL=http://localhost:3002
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    name: frontend-network
    driver: bridge