version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/food_ordering_orders
      - JWT_SECRET=your_jwt_secret_here
      - USER_SERVICE_URL=http://localhost:8000
      - MENU_SERVICE_URL=http://localhost:3001
    depends_on:
      - mongodb
    networks:
      - order-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - order-network
    restart: unless-stopped

networks:
  order-network:
    name: order-network
    driver: bridge

volumes:
  mongodb_data: